version: '3.5'
services:
  ots-share-bundle:
    build:
      context: .
      dockerfile: Dockerfile.bundle
    container_name: ots-share-bundle
    environment:
      - DEV_PORT=${DEV_PORT:-9898}
      - DB_URL=mongodb://ots-share-mongo-local-bundle/ots-share
      - PURGE_TRIGGER_INTERVAL=60000
    ports:
      - '${SERVER_PORT:-8282}:80'
    logging:
      driver: json-file
    depends_on:
      - ots-share-mongo-local-bundle
    links:
      - ots-share-mongo-local-bundle

  ots-share-mongo-local-bundle:
    image: mongo:4.2
    container_name: ots-share-mongo-local-bundle
    expose:
      - 27017